### ISSUE TITLE
README examples are not compilable out of the box

### ISSUE THREAD

**Issue by sharkone** [stretchr/graceful#35]
Hi,
this is really a minor issue but the two examples in the README file cannot be copy/pasted and compiled out of the box.

An updated README can be found here: https://github.com/sharkone/graceful/commit/264135b7c2c488e74fd9ba0575bc4fce6bb279a5 and I can create a pull request if needed.

**Comment by matryer** [comment]
Please do - and we’ll accept it :)

**Comment by matryer** [comment]
We use `go imports` and usually miss issues like that one.  https://github.com/bradfitz/goimports

**Comment by sharkone** [comment]
Here you go: https://github.com/stretchr/graceful/pull/36

**Comment by pushrax** [comment]
Closed by #36
