### ISSUE TITLE
Data race on graceful shutdown via SIGTERM

### ISSUE THREAD

**Issue by dcelasun** [stretchr/graceful#38]
I start the server with `ListenAndServe` as follows:

    server := &graceful.Server{
		Timeout: 10 * time.Second,
		Server: &http.Server{
			Addr:        fmt.Sprintf("%s:%d", s.ListenIp, s.ListenPort),
			ReadTimeout: time.Duration(5) * time.Second,
			Handler:     s,
		},
	}

    err := server.listenAndServe()

When I terminate the process with `SIGTERM` sent via `^C` I get the following race:

    ==================
    WARNING: DATA RACE
    Read by main goroutine:
      github.com/stretchr/graceful.(*Server).Serve()
          /home/dcelasun/go/src/github.com/stretchr/graceful/graceful.go:249 +0xa6c
      github.com/stretchr/graceful.(*Server).ListenAndServe()
          /home/dcelasun/go/src/github.com/stretchr/graceful/graceful.go:110 +0x2ad
      github.com/redacted/server.(*Server).Start()
          /home/dcelasun/go/src/github.com/redacted/server/server.go:88 +0x7c8
      main.main()
          /home/dcelasun/go/src/github.com/redacted/main.go:72 +0xd92

    Previous write by goroutine 13:
      github.com/stretchr/graceful.func·004()
          /home/dcelasun/go/src/github.com/stretchr/graceful/graceful.go:273 +0x9d
      sync.(*Once).Do()
          /build/go/src/go-1.4.2/src/sync/once.go:44 +0xe6
      github.com/stretchr/graceful.(*Server).StopChan()
          /home/dcelasun/go/src/github.com/stretchr/graceful/graceful.go:275 +0x84
      github.com/redacted/server.(*Server).Shutdown()
          /home/dcelasun/go/src/github.com/redacted/server/server.go:192 +0x35

    Goroutine 13 (running) created at:
      github.com/redacted/server.(*Server).Start()
          /home/dcelasun/go/src/github.com/redacted/server/server.go:85 +0x777
      main.main()
          /home/dcelasun/go/src/github.com/redacted/main.go:72 +0xd92
    ==================

I'm blocking on the`StopChan` channel in a separate goroutine:

    go s.Shutdown(server)

    func (s *Server) Shutdown(server *graceful.Server) {
	    <-server.StopChan()
	    s.Close() // Closes other stuff, not relevant to this bug
    }

**Comment by tylerb** [comment]
Thanks for the report! I've got this cleaned up and will be pushing a fix momentarily.
