### ISSUE TITLE
can't customize signal handling

### ISSUE THREAD

**Issue by daniel-garcia** [stretchr/graceful#39]
The current implementation hard codes the signal handling that the graceful shutdown reacts to. In my use case, I want to be able to stop the server with and without signal handling. This is especially useful for tests.

**Comment by daniel-garcia** [comment]
I wanted to open this issue before attempting to create a patch. Would you be open to having this type of behavior in your package?

**Comment by tylerb** [comment]
Thanks for opening the issue to discuss. Does #37 address your issue?

**Comment by daniel-garcia** [comment]
Yes #37 would do just fine.
